### ISSUE TITLE
Are you soon planning to implement channel search?

### ISSUE THREAD

**Issue by kxzo** [adldtd/ytscr#1]
Hey, I really like your work so far. Just wondering if you wanna implement it soon, cause I might urgently need it? xD

**Comment by adldtd** [comment]
First of all, thanks a lot; it really helps. To be honest, I've been kinda off and on with this project (college lol). I'll be working on the channel module after I finish up the playlist one (shouldn't take too long). What parts would you need to scrape?

**Comment by einKnuffy** [comment]
The thing is that I don't really need this feature, if my code would work haha. Just my code is pretty bad and I need to implement it as a nodejs asynchronous function, not only cli.
